[package]
name = "writedisk"
version = "0.7.0"
authors = ["Nicholas Bishop <nbishop@neverware.com>"]
edition = "2018"
repository = "https://github.com/nicholasbishop/writedisk"
license = "Apache-2.0"
description = "Host crate for interacting with Cypress USB devices"
readme = "README.md"

[dependencies]
progress = "0.2.0"
structopt = "0.3.2"
